### ISSUE TITLE
Mispelled "Annotations" as "Admonitions"

### ISSUE THREAD

**Issue by Toddler-Boy** [MNSignalProcessing/BarelyML#1]
Annotations: a note of explanation or comment added to a text or diagram.

Admonition: an act or action of admonishing; authoritative counsel or warning. warn or reprimand someone firmly.

I don't think you meant to use "Admonitions"

**Comment by MNSignalProcessing** [comment]
No, it's not misspelled. That's the exact same term they use in the AsciiDoc Documentation (which has inspired this BarelyML feature): https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#admonitions

I was skeptical in the beginning, too, as I was mainly aware of meanings of the word "admonition" going in the direction of "reprimand". But then I looked it up in a dictionary and it turns out that it can also mean "advice" or "memento", so I think "admonition" is actually a reasonable term to encompass hints, infos, warnings, etc.
