### ISSUE TITLE
Delegation of link clicks

### ISSUE THREAD

**Issue by stijnfrishert** [MNSignalProcessing/BarelyML#3]
Hey, this project looks really convenient. Nice work!

Would it be possible to add something like a `UrlHandler` for handling link clicking? Would work the same as `FileSource`, except that it delegates link clicks.

I need to support clickable sections of text that then play a sound, instead of open a link in the browser.

**Comment by MNSignalProcessing** [comment]
Sure, I'll look into it one of these days. Thanks for the comment.

**Comment by MNSignalProcessing** [comment]
Sorry, "one of these days" turned out to be almost 3 months later... But I finally did release v0.3, which comes not only with a URLHandler class, but also links and images in tables and support for vector graphics (make sure to change your FileHandler implementation accordingly -> needs to return a Drawable instead of an Image).
